module.exports = {
  NONE_EXISTS: 'NONE_EXITS',
  ERROR_NETWORK: 'ERROR_NETWORK',
  ERROR_CONNECTION: 'ERROR_CONNECTION',
  EXISTS: 'ALREADY_EXISTS',
  NONE_EXISTS_STORE: 'NONE_EXISTS_STORE',
  NOT_ENOUGH_PICES: 'NOT_ENOUGH_PICES',
}